#!/bin/zsh

function print_motd(){
  cat /etc/motd
}

function load_ssh_key(){
  if [ -z "$SSH_AUTH_SOCK" ] ; then
    eval `ssh-agent -s` >/dev/null
    ssh-add >/dev/null 2>/dev/null
  fi
}

function setup_aliases(){
  alias l='ls -l'
  alias ll='ls -la'
  alias tmux='tmux -u'
  alias t='tmux -u'
  alias kc='kubectl'
  complete -o default -F __start_kubectl kc
  alias wkc='tmux split-window -h "kubectl get pods -w"; tmux split-window -v "kubectl get prowjobs -w"; tmux split-window -v "kubectl get pipelinerun -w"; jx logs -k'
  alias ccrd='for crd in $(kc get crds | grep -v NAME | awk '"'"'{print $1}'"'"'); do count=$(kc get $crd 2>/dev/null | grep -v NAME | wc -l); echo "$count : $crd"; done | sort -rn | awk '"'"'{if ($1 > 500){print}}'"'"''
}

#function setup_hub(){
#  eval "$(hub alias -s zsh)"
#  source /etc/hub/.hub.zsh_completion.sh
#}

function setup_zsh_completion(){
  #source <(jx completion zsh)
  #source <(kubectl completion zsh)
  if [[ -f /usr/local/google-cloud-sdk/path.zsh.inc ]]
  then
    source '/usr/local/google-cloud-sdk/path.zsh.inc'
  fi
  source '/usr/local/google-cloud-sdk/completion.zsh.inc'
}

function execute_profile_if_exists(){
  if [ -f ~/.zsh_profile ]
  then
    source ~/.zsh_profile
  fi
}

function setup_environment(){

  export HISTSIZE=1000
  export HISTFILESIZE=2000
  export CHARSET=UTF-8
  export JAVA_HOME=$(dirname $(readlink -f $(which java)) | sed 's:/bin::')
  export PATH=$PATH:$JAVA_HOME/bin
  export TERM=xterm-256color
  export GOTESTSUM_FORMAT=short
  execute_profile_if_exists

  TMUX_WINDOW=$(tmux ls | tail -1 | cut -d' ' -f2)
  DEFAULT_KUBE="/home/developer/.kube"
  TMUX_KUBE="${DEFAULT_KUBE}_tw${TMUX_WINDOW}"
  DEFAULT_KUBECONFIG="${DEFAULT_KUBE}/config"
  TMUX_KUBECONFIG="${TMUX_KUBE}/config"

  if [ ! -f ${TMUX_KUBECONFIG} ]
  then
    mkdir -p ${TMUX_KUBE}
    cp ${DEFAULT_KUBECONFIG} ${TMUX_KUBECONFIG}
  fi
  export KUBECONFIG=$TMUX_KUBECONFIG
}

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="geoffgarside"

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# Dir: current working directory
prompt_dir() {
  #prompt_segment blue $CURRENT_FG '%~'
  prompt_segment blue $CURRENT_FG '%2~'
}

plugins=(
  git
  kube-ps1
)

source $ZSH/oh-my-zsh.sh
PROMPT="$(echo -e \\xF0\\x9F\\x99\\x85) $PROMPT"

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
print_motd
setup_zsh_completion
setup_aliases
load_ssh_key
setup_environment
